# Define the number of VMs to create
NUM_VMS = 2

Vagrant.configure("2") do |config|
  config.vm.provider "hyperv"

  (1..NUM_VMS).each do |i|
    if i == 1
      ip_address = "192.168.56.101" # Specific IP for VM1
    else
      ip_address = "192.168.56.#{101+i}" # Sequential IPs for other VMs
    end

    # Format VM name with "VM#!" prefix and the IP address
    vm_name = "Standard-VM#{i}_#{ip_address.gsub('.', '-')}"

    config.vm.define vm_name do |node|
      node.vm.box = "generic/ubuntu1804"
      
      config.vm.provider "hyperv" do |v|
        v.vmname = vm_name
        v.memory = 2048
        v.cpus = 2
      end

      node.vm.network "private_network", ip: ip_address, bridge: "Default Switch"

      # Second network adapter: Bridged network for VM-host communication
      node.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"

      # Share and mount the Vagrant folder
      node.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: false

      # Set the hostname of the VM to match its IP address
      node.vm.provision "shell", inline: <<-SHELL
        # Set User Variable
        USER="ola"
        PASSWORD="ola"
        SSH_PRIVATE_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDPpG4shjevNpoxJxgIYbUQbzzMAY70gtiioI/eI5MCUoDuaMhoVi0s1dVQ87TTJTUQkL59GHzKrc3DMK9XohG3lCnRMfWaeYXKekNuCRAk6vDyN25tZmAnBaanVxGJRnN8GhYF2Larnt/8zcuO3OxI+RstUcmNsje8ZA0jGT9xQFq38WthLWUkISVDrA+YtDQ4avC8VLSFZlVC7vDiNPwng/zkltPfnsrbst8znDA9Qdy5k+lwwQkcEW/gpsUY3xC/afoPEZk0YzHUYHSn2y+d5ZiV6EUsgQoAq1usyPWOMIavRrU1FB/ytvvQ/y7HP9lTJQhT6gO1j/U3NUVe4ayXUWfIlx4n5VQis23K6FjtYCFqVF4HH8tgBgkuEUGSUnk7xhGYQYqqJdlXf9RSsZndXXRpK+v/xgPTlf2txr9Vv1bripfQGcSvraDlYxWsXZDON8zXkNL5QVvnl55R2XonsV1bYzE28VRanfqpjCppKgpb2Tk+HLNMUOU4cuyY5JnsNLOJaS0tJErbVsfGmwaTmQEzYWrDeyw7WL5+dHlqEeo1NQQGKuZtfqq/YPXwl4L2mYJfKOh8L2eHTEIvJkGA5xZttQ3ZZLB7M2+a7VweBWRs4OKIxrOgZ/aqxHUbTd1cJ5/FHaW74J+SaT1OvUHMK0qhCVdTyFPv1lA/zqZzTQ== olaliberace@gmail.com"

        # User setup
        sudo useradd -m -s /bin/bash "$USER" || true
        echo "${USER}:${USER}" | sudo chpasswd
        echo "${USER} ALL=(ALL) NOPASSWD:ALL" | sudo tee "/etc/sudoers.d/${USER}"
        sudo chmod 0440 "/etc/sudoers.d/${USER}"

        # Install necessary packages
        sudo apt-get update && sudo apt-get install -y openssh-server apache2 curl

        # Setup SSH keys for '$USER'
        sudo mkdir -p /home/$USER/.ssh
        sudo chmod 700 /home/$USER/.ssh
        sudo touch /home/$USER/.ssh/authorized_keys
        sudo chmod 600 /home/$USER/.ssh/authorized_keys
        echo "$SSH_PRIVATE_KEY" | sudo tee /home/$USER/.ssh/authorized_keys

        # Set the hostname
        sudo hostnamectl set-hostname #{ip_address}

        # Install Ubuntu Desktop
        sudo apt-get install -y ubuntu-desktop

        sudo reboot
      SHELL
    end
  end
end
