# Define the number of VMs to create
NUM_VMS = 5
#user default created
#USERNAME: standard
#PASSWORD: standard

#create additional user and password
USER = "ubuntu" #Change to name
PASSWORD = "ubuntu" #Chnage to your password
SSH_PRIVATE_KEY = "ssh-rsa AAAAB3NzaC1yghduisuoUGUIGUIF"  #Copy your own SSH key here or leave b;ank if you dont want ssh access
Vagrant.configure("2") do |config|
  # Iterate to configure multiple VMs
  (1..NUM_VMS).each do |i|
    config.vm.define "Standard-VM-#{i}" do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = "Standard-VM-#{i}"

      # VirtualBox specific configuration
      node.vm.provider "virtualbox" do |vb|
        vb.name = "Standard-VM-#{i}"
        vb.memory = "4096"
        vb.cpus = 4
      end

      # First network adapter: Private network for inter-VM communication
      node.vm.network "private_network", ip: "192.168.56.#{10+i}", virtualbox__intnet: true

      # Second network adapter: Bridged network for VM-host communication
      node.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"

      # Provision Docker installation, user setup, and SSH configuration
      node.vm.provision "shell", inline: <<-SHELL
        # Update and upgrade the system
        sudo apt-get update && sudo apt-get upgrade -y

        # Install SSH server and Docker
        sudo apt-get install -y openssh-server apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce

        # Add vagrant user to the docker group
        sudo usermod -aG docker $USER

        # User setup
        sudo useradd -m -s /bin/bash $USER || true
        echo '$USER:$USER' | sudo chpasswd
        echo '$USER ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/$USER
        sudo useradd -m -s /bin/bash standard || true
        echo 'standard:standard' | sudo chpasswd
        echo 'standard ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/standard

        
        # Setup SSH keys for '$USER'
        sudo mkdir -p /home/$USER/.ssh
        sudo chmod 700 /home/$USER/.ssh
        sudo touch /home/$USER/.ssh/authorized_keys
        sudo chmod 600 /home/$USER/.ssh/authorized_keys
        echo "$SSH_PRIVATE_KEY" | sudo tee /home/$USER/.ssh/authorized_keys
      SHELL
    end
  end
end

